# Generated by Django 2.2.4 on 2019-08-16 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_test', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productitemmodel',
            name='price',
            field=models.DecimalField(decimal_places=2, default='0.0', max_digits=11, verbose_name='price'),
        ),
    ]
