# Generated by Django 2.2.4 on 2019-08-16 15:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('task_test', '0002_auto_20190816_1717'),
    ]

    operations = [
        migrations.AddField(
            model_name='productitemmodel',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='task_test.TradeCategoryModel', verbose_name='trade_category'),
        ),
    ]
